### ISSUE TITLE
모음 .이 먹히지 않습니다.

### ISSUE THREAD

**Issue by SeongJunKang** [bab2min/akorn-input#1]
안녕하세요. 
이 옛한글입력기를 사용하는 개발자중 한명입니다.
README에 예시를 든 것 중에  shift + ㅠ, shift + ㅜ 를 하면  ᅔᅕ 이 나오는데
ㅠ. 이나 ㅜ.를하면 나오지않습니다. 
`
curVal = curVal.substring(d[1] - 1, d[1]);
// 모음 처리를 위해 이부분을 추가함
if( '.' == inserted  && (curVal == 'ᅲ' || curVal == 'ᅮ')) {
	var key = curVal == 'ᅲ' ? "ㅠ" :"ㅜ";
	var r = tableAShift[key]; 
	curVal = prefix + r + suffix;
} else {
	if(isVowel(curVal.charCodeAt(0))) {
		curVal = prefix + curVal + reassemble(inserted, tablePC, tableCP) + suffix;
	} else {
		var t1 = tablePA, t2 = tableAP;
		if(this.compBegin < d[1]-1 && isVowel(prefix.charCodeAt(d[1]-2))) {
			t1 = tablePC, t2 = tableCP;
		}
		var r = reassemble(curVal + inserted, t1, t2);
		if(r.length > 1) {
			this.compBegin = prefix.length + r.length - 1;
		}
		curVal = prefix + r + suffix;
	}
}
`

**Comment by bab2min** [comment]
버그 제보해주셔서 감사합니다. 확인해보니 자음에 .가 붙은 경우만 변환되도록 짜여있었네요.
공유해주신 해결책 참고하여 0.1.1 버전을 업데이트하였습니다.

https://github.com/bab2min/akorn-input/commit/42e0d257b0674c41a0413fed8915f6a4b4512b3a

이제 초성과 결합되지 않은 ㅜ, ㅠ에 대해서 .가 붙는 경우 정상적으로 ᅔᅕ로 변환됩니다.
